
[General]
	#The range of the explosion of a coal block.
	#Range: 0.0 ~ 256.0
	explosionRange = 5.0
	#Whether an exploding coal block should cause fire.
	causeFire = true
	#A list of extra configured items that can cause coal to explode
	configuredIgniters = [
		"tfc:metal/pickaxe/wrought_iron",
		"tfc:metal/propick/wrought_iron",
		"tfc:metal/axe/wrought_iron",
		"tfc:metal/shovel/wrought_iron",
		"tfc:metal/hoe/wrought_iron",
		"tfc:metal/chisel/wrought_iron",
		"tfc:metal/hammer/wrought_iron",
		"tfc:metal/saw/wrought_iron",
		"tfc:metal/javelin/wrought_iron",
		"tfc:metal/sword/wrought_iron",
		"tfc:metal/mace/wrought_iron",
		"tfc:metal/knife/wrought_iron",
		"tfc:metal/scythe/wrought_iron",
		"tfc:metal/pickaxe/steel",
		"tfc:metal/propick/steel",
		"tfc:metal/axe/steel",
		"tfc:metal/shovel/steel",
		"tfc:metal/hoe/steel",
		"tfc:metal/chisel/steel",
		"tfc:metal/hammer/steel",
		"tfc:metal/saw/steel",
		"tfc:metal/javelin/steel",
		"tfc:metal/sword/steel",
		"tfc:metal/mace/steel",
		"tfc:metal/knife/steel",
		"tfc:metal/scythe/steel",
		"tfc:metal/pickaxe/black_steel",
		"tfc:metal/propick/black_steel",
		"tfc:metal/axe/black_steel",
		"tfc:metal/shovel/black_steel",
		"tfc:metal/hoe/black_steel",
		"tfc:metal/chisel/black_steel",
		"tfc:metal/hammer/black_steel",
		"tfc:metal/saw/black_steel",
		"tfc:metal/javelin/black_steel",
		"tfc:metal/sword/black_steel",
		"tfc:metal/mace/black_steel",
		"tfc:metal/knife/black_steel",
		"tfc:metal/scythe/black_steel",
		"tfc:metal/pickaxe/blue_steel",
		"tfc:metal/propick/blue_steel",
		"tfc:metal/axe/blue_steel",
		"tfc:metal/shovel/blue_steel",
		"tfc:metal/hoe/blue_steel",
		"tfc:metal/chisel/blue_steel",
		"tfc:metal/hammer/blue_steel",
		"tfc:metal/saw/blue_steel",
		"tfc:metal/javelin/blue_steel",
		"tfc:metal/sword/blue_steel",
		"tfc:metal/mace/blue_steel",
		"tfc:metal/knife/blue_steel",
		"tfc:metal/scythe/blue_steel",
		"tfc:metal/pickaxe/red_steel",
		"tfc:metal/propick/red_steel",
		"tfc:metal/axe/red_steel",
		"tfc:metal/shovel/red_steel",
		"tfc:metal/hoe/red_steel",
		"tfc:metal/chisel/red_steel",
		"tfc:metal/hammer/red_steel",
		"tfc:metal/saw/red_steel",
		"tfc:metal/javelin/red_steel",
		"tfc:metal/sword/red_steel",
		"tfc:metal/mace/red_steel",
		"tfc:metal/knife/red_steel",
		"tfc:metal/scythe/red_steel"
		]

